project:
  type: book

book:
  title: "SEFSC-SEDAR-CR-84-RW"
  chapters:
    - index.qmd

format: 
  pdf:
    number-sections: false
    css: |
      .table tr {
        page-break-inside: avoid;
      }
    include-in-header: 
      - text: |
          \raggedright
          \usepackage{caption}
          \captionsetup[table]{justification=raggedright, format=plain, indention=1em, singlelinecheck=false}
          \captionsetup[figure]{justification=raggedright, format=plain, indention=1em, singlelinecheck=false}

editor: visual



